### PR TITLE
Feat: Upload to all profiles

### PR DESCRIPTION
**Pull request by wewawa**
Add file upload commands able to all profiles at once.

## issues

- [希望多重上下文批量同步支持 #125](https://github.com/Natizyskunk/vscode-sftp/issues/125)
- [one file to n servers #156](https://github.com/Natizyskunk/vscode-sftp/issues/156)
- [upload local files to multiple servers at once. #127](https://github.com/Natizyskunk/vscode-sftp/issues/127)
- [Multiples profiles and multiples contexts #277](https://github.com/Natizyskunk/vscode-sftp/issues/277)

## new commands

- Upload File To All Profiles
- Upload Active File To All Profiles
- Upload Folder To All Profiles
- Upload Project To All Profiles
- Force Upload To All Profiles

### CODE REVIEW

**Comment by wewawa** [comment]
## new commands

- Upload File To All Profiles
- Upload Active File To All Profiles
- Upload Folder To All Profiles
- Upload Active Folder To All Profiles
- Upload Project To All Profiles
- Force Upload To All Profiles

**Comment by Natizyskunk** [comment]
@wewawa,

Thanks a lot. I'll try to review and merge it in the coming weeks.

**Review by Natizyskunk — APPROVED** [review]
Perfect :)

**Comment by Natizyskunk** [comment]
has been merged in pull request #356.

**Comment by netizen-ais** [comment]
I'd love these to show only in workspaces where I've got more than one profile

**Pull request merged**
