### PR TITLE
Enhance sftp interactiveAuth mode

### PR DESCRIPTION
**Pull request by lacastorine**
SFTP : interactiveAuth : add ability to pass predefined phrases in 'keyboard-interactive' auth variant.

### CODE REVIEW

**Comment by lacastorine** [comment]
This also may be a 'hack' solution for - https://github.com/Natizyskunk/vscode-sftp/issues/62 - for me for some sftp ssh2 can't auth with name+password, but it successfully authenticate when enter password via user prompt.

**Comment by Natizyskunk** [comment]
@lacastorine,

I'am actually glad that someone could finally find a "fix" for this bug.

can you confirm me that this is actually working as expected ?
Have you built the vsix extension and tried it ?

Also just before merging anything, can you follow the guidelines available [here](https://github.com/Natizyskunk/vscode-sftp/issues/80) on how to open a Pull Request please ?  😀

Thank you very much for your help !

**Comment by lacastorine** [comment]
@Natizyskunk 

> Have you built the vsix extension and tried it ?

sorry, no. I just compile and change `extension.js` file... thanks you've asked - with final vsix I've noticed an error and fixed it (mask phrases in interactiveAuth prop, push boolean to tryKeyboard ssh2 prop, fix extension config check on start). (squashed into one commit)

> can you confirm me that this is actually working as expected ?

yes, now I can confirm that it works for me as expected

> can you follow the guidelines

edit title and description

**Comment by lacastorine** [comment]
@Natizyskunk, is there anything else you want me to fix in this PR?

**Comment by DamirPecnik** [comment]
When will this get merged?

**Comment by Natizyskunk** [comment]
I'll try to merge it as soon as possible, I hope to have time this week or the next one.

**Comment by Natizyskunk** [comment]
has been merged in pull-request #114.

**Comment by Natizyskunk** [comment]
@[DamirPecnik](https://github.com/DamirPecnik), 

you can find the fix merged inside the latest request availaible [here](https://github.com/Natizyskunk/vscode-sftp/releases/latest/). 😉

**Pull request merged**
