### PR TITLE
fix connect sftp with public key

### PR DESCRIPTION
**Pull request by inu1255**
ssh2 issue: https://github.com/mscdex/ssh2/issues/989

### CODE REVIEW

**Comment by eb-360vier** [comment]
Finally! The only fix I was able to find to finally be able to connect using keys.

@Natizyskunk can you please merge?

**Comment by Natizyskunk** [comment]
@eb-360vier I'm gonna take a look at it asap 🙂

**Comment by Natizyskunk** [comment]
has been merged in #359.

**Comment by bangnoyan** [comment]
hi. the sftp has been doing fine all along till today when i suddenly received an error message [06-17 11:16:38] [error] Error: ENOENT: no such file or directory, open 'c:\Users\xxxxxx......

Although the file is there, it says :

Detail: Unable to read file 'c:\Users\[my file path]' (Error: Unable to resolve nonexistent file 'c:\Users\[my file path]')
    at e.MainThreadDocuments.$tryOpenDocument (vscode-file://vscode-app/c:/Users/user1/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2304:40807) 

How to solve this error? Pls advise. Thanks.

**Pull request merged**
