### PR TITLE
Add deletions support  to "Upload Changed files" command

### PR DESCRIPTION
**Pull request by brykov**
Add deletions support to "Upload Changed files" command

### CODE REVIEW

**Comment by Natizyskunk** [comment]
@brykov,

Can you confirm me that this is actually working as expected ?
Have you built the vsix extension and tried it ?

Also just before merging anything, can you follow the guidelines available https://github.com/Natizyskunk/vscode-sftp/issues/80 on how to open a Pull Request please ? 😀

Thank you very much for your help !

**Comment by brykov** [comment]
@Natizyskunk, I can confirm that it works as expected. I have built the vsix and tried it myself. 
I think my PR follows the guidelines.

**Comment by Natizyskunk** [comment]
I'll take a look this week-end 👍

**Comment by Natizyskunk** [comment]
Has been merged in pull-request #117.

**Comment by Natizyskunk** [comment]
@brykov, 
you can find the fix merged inside the latest release availaible [here](https://github.com/Natizyskunk/vscode-sftp/releases/latest/). 😉

**Comment by brykov** [comment]
awesome, thank you!

**Comment by Natizyskunk** [comment]
You're welcome :)

**Pull request merged**
